language: csharp
solution: ./ChessGUI/ChessGUI.sln

install:
  - nuget restore ./ChessGUI/ChessGUI.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./ChessGUI/ChessGUI.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./ChessGUI.Tests/bin/Release/ChessGUI.Tests.dll
