language: csharp
script:
  - xbuild /p:Configuration=Debug ./ChessGUI/ChessGUI.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./ChessGUI/ChessGUI.sln
after_script:
  - nunit-console Tests/bin/Debug/Tests.dll
