language: csharp
solution: ./ChessGUI/ChessGUI.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./ChessGUI/ChessGUI.sln

script:
  - xbuild ./src/yoursolution.sln
  - nunit-console ./src/SomeLibrary.Tests/bin/Debug/SomeLibrary.Tests.dll
